server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: jamie
    password: jamie
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgresSQLDialect
#          format_sql: "true"
#      hibernate:
#        ddl-auto: update
#      show-sel: "true"
