version: "3.0"

services:
  postgres:
    image: postgres
    container_name: spring_microservices_postgres
    environment:
      POSTGRES_USER: jamie
      POSTGRES_PASSWORD: jamie
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - ./docker/postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgres: